function centerbox(coordinates,id){
    if(id=='he_bei'){
		console.log(coordinates);
		coordinates[0]=116.23;
		coordinates[1]=39.74;
	}
	if(id=='shan_dong'){
		console.log(coordinates);
		coordinates[0]=119.00;
		coordinates[1]=36.40;
	}
	if(id=='hei_long_jiang'){
		console.log(coordinates);
		coordinates[0]=127.92;
		coordinates[1]=49.50;
	}
	if(id=='yun_nan'){
		console.log(coordinates);
		coordinates[0]=102.92;
		coordinates[1]=26.00;
	}
	if(id=='xi_zang'){
		console.log(coordinates);
		coordinates[0]=91.92;
		coordinates[1]=32.36;
	}
	if(id=='gan_su'){
		console.log(coordinates);
		coordinates[0]=103.40;
		coordinates[1]=38.36;
	}
	if(id=='nei_meng_gu'){
		console.log(coordinates);
		coordinates[0]=113.40;
		coordinates[1]=47.36;
	}
    if(id=='xin_jiang'){
		console.log(coordinates);
		coordinates[0]=88.40;
		coordinates[1]=43.36;
	}
	if(id=='si_chuan'){
		console.log(coordinates);
		coordinates[0]=104.06;
		coordinates[1]=30.67;
	}
	return coordinates;
}